AppMvc.Net/Areas/Product/Controllers/ViewProductController.cs
using AppMvc.Net.Areas.Product.Models;
using AppMvc.Net.Models;
using AppMvc.Net.Models.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppMvc.Net.Areas.Product.Controllers
{
    [Area("Product")]
    public class ViewProductController : Controller
    {
        private readonly ILogger<ViewProductController> _logger;
        private readonly AppDbContext _context;


        public ViewProductController(ILogger<ViewProductController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;

        }

        // /post/
        // /post/{categoryslug?}
        [Route("/product/{categoryslug?}")]
        public IActionResult Index(string categoryslug, [FromQuery(Name = "p")] int currentPage, int pagesize)
        {

            var categories = GetCategories();
            ViewBag.categories = categories;
            ViewBag.categoryslug = categoryslug;

            CategoryProduct category = null;

            if (!string.IsNullOrEmpty(categoryslug))
            {
                category = _context.CategoryProducts.Where(c => c.Slug == categoryslug)
                                    .Include(c => c.CategoryChildren)
                                    .FirstOrDefault();

                if (category == null)
                {
                    return NotFound("Không thấy category");
                }
            }

            var products = _context.Products
                                .Include(p => p.Author)
                                .Include(p => p.Photos)
                                .Include(p => p.ProductCategoryProducts)
                                .ThenInclude(p => p.Category)
                                .AsQueryable();

            products = products.OrderByDescending(p => p.DateUpdated);

            if (category != null)
            {
                var ids = new List<int>();
                category.ChildCategoryIDs(null, ids);
                ids.Add(category.Id);


                products = products.Where(p => p.ProductCategoryProducts.Where(pc => ids.Contains(pc.CategoryID)).Any());


            }

            int totalProducts = products.Count();
            if (pagesize <= 0) pagesize = 12;
            int countPages = (int)Math.Ceiling((double)totalProducts / pagesize);

            if (currentPage > countPages) currentPage = countPages;
            if (currentPage < 1) currentPage = 1;

            var pagingModel = new PagingModel()
            {
                countpages = countPages,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new
                {
                    p = pageNumber,
                    pagesize = pagesize
                })
            };

            var productsInPage = products.Skip((currentPage - 1) * pagesize)
                             .Take(pagesize);


            ViewBag.pagingModel = pagingModel;
            ViewBag.totalPosts = totalProducts;



            ViewBag.category = category;
            return View(productsInPage.ToList());
        }

        [Route("/productdetail/{productslug}.html")]
        public IActionResult Detail(string productslug)
        {
            Console.WriteLine("aaaaaaa:", productslug);
            var categories = GetCategories();
            ViewBag.categories = categories;

            var product = _context.Products.Where(p => p.Slug == productslug)
                               .Include(p => p.Author).Include(p => p.Photos)
                               .Include(p => p.ProductCategoryProducts)
                               .ThenInclude(pc => pc.Category)
                               .FirstOrDefault();

            if (product == null)
            {
                return NotFound("Không thấy sản phẩm");
            }

            CategoryProduct category = product.ProductCategoryProducts.FirstOrDefault()?.Category;
            ViewBag.category = category;

            var otherProducts = _context.Products.Where(p => p.ProductCategoryProducts.Any(c => c.Category.Id == category.Id))
                                            .Where(p => p.Id != product.Id)
                                            .OrderByDescending(p => p.DateUpdated)
                                            .Take(5);
            ViewBag.otherProducts = otherProducts;

            return View(product);
        }

        private List<CategoryProduct> GetCategories()
        {
            var categories = _context.CategoryProducts
                            .Include(c => c.CategoryChildren)
                            .AsEnumerable()
                            .Where(c => c.ParentCategory == null)
                            .ToList();
            return categories;
        }

        /// Thêm sản phẩm vào cart



    }
}

AppMvc.Net/Areas/Product/Views/ViewProduct/Detail.cshtml
@* @model ProductModel
@using AppMvc.Net.Components

@{
List<CategoryProduct> categories = ViewBag.categories as List<CategoryProduct>;
CategoryProduct category = ViewBag.category as CategoryProduct;
ViewData["Title"] = Model.Title;

IQueryable<ProductModel> otherProducts = ViewBag.otherProducts as IQueryable<ProductModel>;
}

<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="~/">Home</a></li>
@if (category != null)
{
var li = category.ListParents();
foreach (var l in li)
{
<li class="breadcrumb-item">
<a asp-action="Index" asp-route-categoryslug="@l.Slug">@l.Title</a>
</li>
}
<li class="breadcrumb-item">
<a asp-action="Index" asp-route-categoryslug="@category.Slug">@category.Title</a>
</li>
}
</ol>
</nav>

<div class="detailpost">
<h1>@Model.Title</h1>
<div class="sapo">
@Model.Description
</div>
<div>
<p>
Giá: <strong>@Model.Prices</strong>

<form asp-area="Cart" asp-controller="ViewCart" asp-action="AddItem" method="post">
<input type="hidden" name="productId" value="@Model.Id" />
<input type="hidden" name="quantity" value="1" />
<button type="submit" class="btn btn-danger">Add to cart</button>
</form>


</p>
</div>
<div>
<i>Cập nhật: @Model.DateUpdated</i> /
Tác giả: <strong>@Model.Author.UserName</strong>
</div>

@if (Model.Photos.Any())
{
<div class="d-flex flex-wrap">
@foreach (var photo in Model.Photos)
{
<img class="w-50" src="/contents/Products/@photo.FileName" />
}
</div>
}



<hr>

@Html.Raw(Model.Content)

</div>




@section Sidebar {
@await Component.InvokeAsync("AppMvc.Net.Components.CategoryProductSideBar",
new CategoryProductSideBar.CategorySidebarData()
{
Categories = categories,
level = 0,
categoryslug = category.Slug
})

<ul class="list-group">
@foreach (var product in otherProducts)
{
<li class="list-group-item">
<a asp-controller="ViewProduct" asp-action="Detail" asp-route-productslug="@product.Slug">
@product.Title
</a>
</li>
}
</ul>
} *@
@model ProductModel
@using AppMvc.Net.Components

@{ 
    List<CategoryProduct> categories = ViewBag.categories as List<CategoryProduct>;
    CategoryProduct category = ViewBag.category as CategoryProduct;  
    ViewData["Title"] = Model.Title;    
    IQueryable<ProductModel> otherProducts = ViewBag.otherProducts as IQueryable<ProductModel>;
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/">Home</a></li>
    @if (category != null)
    {
        var li = category.ListParents();
        foreach (var l in li)
        {
            <li class="breadcrumb-item">
                <a asp-action="Index" asp-route-categoryslug="@l.Slug">@l.Title</a>
            </li>
        }
        <li class="breadcrumb-item">
                <a asp-action="Index" asp-route-categoryslug="@category.Slug">@category.Title</a>
        </li>
    } 
  </ol>
</nav>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="flex flex-column">
                <div id="mainImage" class="center Oj2Oo7">
                    <img class="img-fluid main-img-fixed" src="/contents/Products/@Model.Photos.FirstOrDefault()?.FileName" alt="Main Product Image">
                </div>
            </div>
            <div class="mt-3">
                <div class="d-flex justify-content-start">
                    @foreach (var photo in Model.Photos)
                    {
                        <div class="thumbnail-container mx-1">
                            <img class="img-thumbnail" src="/contents/Products/@photo.FileName" alt="Product Thumbnail" onclick="updateMainImage('@photo.FileName')">
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h1>@Model.Title</h1>
            <p>@Model.Description</p>
            <p>
                <span class="h4">Giá: <strong>@Model.Prices</strong></span>
            </p>
            <form asp-area="Cart" asp-controller="ViewCart" asp-action="AddItem" method="post">
                <input type="hidden" name="productId" value="@Model.Id" />
                <input type="hidden" name="quantity" value="1" />
                <button type="submit" class="btn btn-danger btn-lg btn-block">Add to cart</button>
            </form>
            <p class="mt-3"><i>Cập nhật: @Model.DateUpdated</i></p>
            <p><strong>Tác giả:</strong> @Model.Author.UserName</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            @Html.Raw(Model.Content)
        </div>
    </div>
</div>

@section Sidebar {
    @await Component.InvokeAsync("AppMvc.Net.Components.CategoryProductSideBar", 
        new CategoryProductSideBar.CategorySidebarData()
        {
            Categories = categories,
            level = 0,
            categoryslug = category.Slug
        })

    <div class="list-group mt-4">
        @foreach (var product in otherProducts)
        {
            <a href="@Url.Action("Detail", "ViewProduct", new { productslug = product.Slug })" class="list-group-item list-group-item-action">
                @product.Title
            </a>
        }
    </div>
}
<script>
function updateMainImage(imageUrl) {
    document.querySelector('#mainImage img').src = '/contents/Products/' + imageUrl;
}
</script>

AppMvc.Net/Areas/Product/Views/ViewProduct/Index.cshtml
@model List<ProductModel>

@using AppMvc.Net.Components;

@{ 
    List<CategoryProduct> categories = ViewBag.categories as List<CategoryProduct>;
    CategoryProduct category = ViewBag.category as CategoryProduct;  
    ViewData["Title"] = (category != null) ? category.Title : 
                        "Tất cả sản phẩm";
}


<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/">Home</a></li>
    @if  (category != null)
    {
        var li = category.ListParents();
        foreach (var l in li)
        {
            <li class="breadcrumb-item">
                <a asp-action="Index" asp-route-categoryslug="@l.Slug">@l.Title</a>
            </li>
        }
    } 
  </ol>
</nav>



<h1>@ViewData["Title"]</h1>
@if (category != null)
{
    <p>@category.Description</p>
}
else
{
    <p>Toàn bộ sản phẩm trong tất cả danh mục...</p>
}
<hr>
<div class="d-flex flex-wrap justify-content-between">
    @foreach (var product in Model)
    {
var srcImg = "/contents/icon.jpg";
        if (product.Photos.Any())
        {
            srcImg = $"/contents/Products/{product.Photos.FirstOrDefault().FileName}";
        }
        <a class="card card-link" style="width: 20rem;"href="@Url.Action("Detail", "ViewProduct", new { productslug = product.Slug })">
            <img src="@srcImg" class="card-img-top" alt="..." style="width: 100%; height: 300px; object-fit: cover;">
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">@product.Title</h5>
                <div class="mt-auto">
                    <p>Giá: <strong>@product.Prices</strong></p>
                    <form asp-area="Cart" asp-controller="ViewCart" asp-action="AddItem" method="post">
                        <input type="hidden" name="productId" value="@product.Id" />
                        <input type="hidden" name="quantity" value="1" />
                        <button type="submit" class="btn btn-danger">Add to cart</button>
                    </form>
                </div>
            </div>
        </a>

        

    }
</div>

@section Sidebar {
    @await Component.InvokeAsync("AppMvc.Net.Components.CategoryProductSideBar", 
        new CategoryProductSideBar.CategorySidebarData()
        {
            Categories = categories,
            level = 0,
            categoryslug = ViewBag.categoryslug
        })
}


<partial name="_PagingXTL" model="@ViewBag.pagingModel" />

AppMvc.Net/Areas/Product/Views/ViewProduct/_LayoutProduct.cshtml
@{
    Layout = "_SiteLayout";
}


<div class="row">
    <div class="col-md-2">
        @RenderSection("Sidebar", false)
    </div>
    <div class="col-md-10">
        @RenderBody()
    </div>

</div>